#test.mac
/control/verbose 2
/run/verbose 2
/leap/phys/addPhysics polarized


/run/printProgress 1

/run/initialize

#-----------geometry-----------------------------
/leap/det/SetCoreThick 75 mm
/leap/det/SetConvThick 1.75 mm

/leap/det/Setnumberofcrystals one
/leap/beamline/Collimator -1 mm
/leap/det/dCalo 40 cm

/leap/det/update


/polarization/manager/verbose 1
/polarization/volume/set IronCore 0. 0. 1
/polarization/volume/list

#-----------particle-gunlike-------------------------------
/gps/energy 60 MeV
/gps/number 100000
/gps/particle e-
/gps/pos/centre 0.0 0.0 -3650.0 mm 

#---------gps-commands-------------------------------------
#simply comment if not needed
#2D-Beam
/gps/ene/type Gauss
/gps/ene/sigma 2.547 MeV
/gps/pos/type Beam
/gps/pos/sigma_x 0.001  mm
/gps/pos/sigma_y 0.001  mm
/gps/ang/type beam2d
/gps/ang/sigma_x 0.003 rad
/gps/ang/sigma_y 0.003 rad
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0

#------------------------------------------------------
#run in both polarization directions

/gps/polarization 0. 0. 1

/run/beamOn 1

#/gps/polarization 0. 0. -1

#/run/beamOn 1
